apiVersion: v1
kind: Service
metadata:
  name: nugget-api
  namespace: nugget
spec:
  selector:
    app: nugget-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nugget-web
  namespace: nugget
spec:
  selector:
    app: nugget-web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
